//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works
    {
        public int Id { get; set; }
        public string Vakancy { get; set; }
        public string Region { get; set; }
        public string Salary { get; set; }
        public string Organization { get; set; }
        public string Person { get; set; }
        public string Phone { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public int RegionId { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual Region Region1 { get; set; }
        public virtual Organization Organization1 { get; set; }
    }
}
