//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        public int Id { get; set; }
        public string Vakancy { get; set; }
        public string RegionName { get; set; }
        public string Salary { get; set; }
        public string OrganizationName { get; set; }
        public string Person { get; set; }
        public string Phone { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public int RegionId { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
